### ISSUE TITLE
Разные php-fpm pool

### ISSUE THREAD

**Issue by kerstvo** [Umkus/nginx-boilerplate#40]
Во-первых, спасибо за отличную работу. Всё очень хорошо структурировано.
Во-вторых есть вопрос. Я еще не очень разобрался с пулами php-fpm, но сейчас у меня есть 2 пула, один для тестов и второй для продакшена. Как мне указать какой использовать? Спасибо! Или просто использовать один пул?

**Comment by Umkus** [comment]
Только что вышел `v0.2.0`. Теперь есть возможность указать разные бэкенды и использовать их по своему усмотрению в единственном изменяемом файле вашего сайта. Больше никаких bootstrap-ов.
