### ISSUE TITLE
JavaScript content type

### ISSUE THREAD

**Issue by NARKOZ** [Umkus/nginx-boilerplate#91]
According to https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages:javascript-mime-type:

>Servers should use text/javascript for JavaScript resources.

and https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript:

>Per the HTML specification, JavaScript files should always be served using the MIME type text/javascript.

>It's the only MIME type guaranteed to work now and into the future.

However currently js files are set to be served with `application/javascript` Content-Type:

https://github.com/nginx-boilerplate/nginx-boilerplate/blob/ee26cdced0e5969dc88875f1e23c8aafc6491cf7/boilerplate/system/mime_types.conf#L14

**Comment by Umkus** [comment]
This bit came straight from the original [nginx mime-type config](https://github.com/nginx/nginx/blob/master/conf/mime.types#L8).

Also if you check you could see that google.com, amazon.com and microsoft.com each use their own mime-type definitions for javascript files (`text/javascript`, `application/x-javascript` and `application/javascript` respectively).

**Comment by NARKOZ** [comment]
There is an active draft which will make `application/javascript` absolute in the near future https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/

Also see discussion in https://github.com/golang/go/issues/32351

**Comment by Umkus** [comment]
Judging by the various discussions and the actual usage on the [top popular websites](https://en.wikipedia.org/wiki/List_of_most_popular_websites) and CDNs, this topic still remains controversial.
[The similar ticket](https://trac.nginx.org/nginx/ticket/1407) was already closed as invalid on nginx side.

For the time being I would prefer to inherit mime types from nginx itself and abide by the current version of `RFC4329`. Later, when the RFC is updated we can change the mime-type, even if nginx project doesn't.
